# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'products', '0001_initial'), (b'products', '0002_auto_20170214_1731'), (b'products', '0003_auto_20170214_1838'), (b'products', '0004_auto_20170214_1848'), (b'products', '0005_itemcategory'), (b'products', '0006_auto_20170215_0759'), (b'products', '0007_auto_20170215_0822'), (b'products', '0008_auto_20170215_0831'), (b'products', '0009_auto_20170215_1321'), (b'products', '0010_auto_20170215_1653'), (b'products', '0011_auto_20170215_1716'), (b'products', '0012_auto_20170216_1057'), (b'products', '0013_auto_20170216_1105'), (b'products', '0014_auto_20170216_1106'), (b'products', '0015_auto_20170216_1408')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('sku', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('upc', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=6)),
                ('active', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Maybe')], default=1)),
                ('available', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ItemCategory')),
                ('created', models.DateTimeField(default=datetime.datetime.now, max_length=256)),
                ('name', models.CharField(default='', max_length=256)),
                ('size_value', models.CharField(max_length=256)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('type_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ItemType')),
                ('vintage', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('category', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('type_num', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=256)),
            ],
        ),
    ]
