# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170214_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vintage',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
