# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170214_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size_value',
            field=models.CharField(max_length=256),
        ),
    ]
