# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_itemcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cat_name',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ItemCategory'),
        ),
    ]
