# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170215_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='X',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Y',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='x',
            name='Y',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Y'),
        ),
    ]
