# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170215_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ItemCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ItemType'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='type_num',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
