# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20170215_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_category',
        ),
        migrations.AddField(
            model_name='item',
            name='category_num',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ItemCategory'),
        ),
    ]
