# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170215_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='x',
            name='Y',
        ),
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.NullBooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='X',
        ),
        migrations.DeleteModel(
            name='Y',
        ),
    ]
