# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20170216_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, null=True),
        ),
    ]
