# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20170216_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category_num',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ItemCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ItemType'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vintage',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
